require('dotenv').config();
const connectDB = require('./config/db');
const Admin = require('./models/Admin');
const Contact = require('./models/Contact');
const Vendor = require('./models/Vendor');
const Testimonial = require('./models/Testimonial');
const Project = require('./models/Project');

const projects = [
  { title: 'Rae Hotel Delhi', slug: 'rae-hotel-delhi', code: '#OS-DEL-01', client: 'ABC Hospitality', location: 'Civil Lines, Delhi', scale: '6,500 sq.ft', status: 'In Progress', progress: 40, fees: 600000, feeStatus: 'DUE SOON', subtitle: 'Boutique Hotel • New Delhi' },
  { title: 'Nova Café Mumbai', slug: 'nova-cafe-mumbai', code: '#OS-BOM-08', client: 'Mehta F&B Group', location: 'Bandra West, Mumbai', scale: '2,100 sq.ft', status: 'In Progress', progress: 70, fees: 450000, feeStatus: 'PAID FULL', subtitle: 'Café • Mumbai' },
  { title: 'Urban Retail Gallery', slug: 'urban-retail-gallery', code: '#OS-BLR-14', client: 'Urban Living Co.', location: 'Indiranagar, BLR', scale: '3,400 sq.ft', status: 'Confirmed', progress: 15, fees: 300000, feeStatus: 'DUE RETAINER', subtitle: 'Retail • Bengaluru' },
  { title: 'The Work Loft Gurgaon', slug: 'the-work-loft-gurgaon', code: '#OS-DEL-04', client: 'Apex Studio Spaces', location: 'CyberHub, Gurgaon', scale: '8,200 sq.ft', status: 'In Progress', progress: 85, fees: 500000, feeStatus: 'DUE TRANCHE', subtitle: 'Workspace • Gurgaon' },
  { title: 'Artisanal Store Jaipur', slug: 'artisanal-store-jaipur', code: '#OS-JAI-02', client: 'Kala Craft Collective', location: 'C-Scheme, Jaipur', scale: '1,800 sq.ft', status: 'In Progress', progress: 35, fees: 350000, feeStatus: 'PAID RETAINER', subtitle: 'Retail • Jaipur' },
  { title: 'Komorebi Villa Alibaug', slug: 'komorebi-villa-alibaug', code: '#OS-ALI-01', client: 'Nair Heritage Living', location: 'Alibaug Coastal, MH', scale: '5,200 sq.ft', status: 'Completed', progress: 100, fees: 1400000, feeStatus: 'SETTLED', subtitle: 'Residence • Alibaug' },
  { title: 'Studio Atelier Chandigarh', slug: 'studio-atelier-chandigarh', code: '#OS-IXC-03', client: 'Tricity Media Lab', location: 'Sector 8, Chandigarh', scale: '3,100 sq.ft', status: 'In Progress', progress: 60, fees: 280000, feeStatus: 'DUE IN 4 DAYS', subtitle: 'Studio • Chandigarh' },
  { title: 'Saffron Terrace Bangalore', slug: 'saffron-terrace-bangalore', code: '#OS-BLR-21', client: 'Deccan Bistro Ltd', location: 'Lavelle Road, BLR', scale: '4,000 sq.ft', status: 'Confirmed', progress: 10, fees: 400000, feeStatus: 'DUE RETAINER', subtitle: 'Hospitality • Bengaluru' },
];

const contacts = [
  { name: 'Tanya Sharma', email: 'tanya.sharma@culturecraft.in', phone: '+91 98988 44855', message: 'Protected 19th-century lime-plaster haveli pavilion. Requires specialized conservation-grade MEP conduits and indigenous red sandstone flooring.', status: 'NEW', org: 'CultureCraft Heritage Foundation • Jaipur Chapter', service: 'Retail & Art Gallery', scope: 'Scope: 4,500 sq.ft turnkey', location: 'Jaipur, Rajasthan', typology: 'Retail & Art Gallery', footprint: '4,500 sq.ft', budget: '₹35,00,000', brief: 'Protected 19th-century lime-plaster haveli pavilion. Requires specialized conservation-grade MEP conduits and indigenous red sandstone flooring.', address: 'C-Scheme, Ashok Nagar, Jaipur, RJ 302001', ref: '#ENG-9042', assignee: { initials: 'ER', name: 'Elena Rostova', role: 'Lead Spatial Curator' }, ip: '14.139.24.81' },
  { name: 'Karan Mehta', email: 'karan@mehtahospitality.com', phone: '+91 98200 11245', message: 'Colonial-era warehouse shell with original exposed rafters. Needs a full MEP refresh while retaining the weathered façade and teak trusses.', status: 'IN DISCUSSION', org: 'Mehta Hospitality Group • Mumbai', service: 'Café Interior Architecture', scope: 'Scope: Adaptive reuse, heritage building', location: 'Bandra, Mumbai', typology: 'Café Interior Architecture', footprint: '2,100 sq.ft', budget: '₹18,50,000', brief: 'Colonial-era warehouse shell with original exposed rafters. Needs a full MEP refresh while retaining the weathered façade and teak trusses.', address: 'Carter Road, Bandra West, Mumbai, MH 400050', ref: '#ENG-9038', assignee: { initials: 'AM', name: 'Aditi Mehra', role: 'Principal Architect' }, ip: '103.21.58.14' },
  { name: 'Ananya Sood', email: 'ananya.sood@indiatimes.com', phone: '+91 98450 77321', message: 'Double-height penthouse shell with a north-facing terrace. Client requests integrated bespoke joinery in walnut and lime-washed walls throughout.', status: 'CONFIRMED', org: 'Sood Residences • Bengaluru', service: 'Residential Penthouse', scope: 'Scope: Interior architecture + bespoke furniture', location: 'Indiranagar, Bengaluru', typology: 'Residential Penthouse', footprint: '3,800 sq.ft', budget: '₹28,00,000', brief: 'Double-height penthouse shell with a north-facing terrace. Client requests integrated bespoke joinery in walnut and lime-washed walls throughout.', address: '100 Ft Road, Indiranagar, Bengaluru, KA 560038', ref: '#ENG-9031', assignee: { initials: 'DS', name: 'Devika Sharma', role: 'Interior Lead' }, ip: '49.36.180.77' },
  { name: 'Raghav Singhania', email: 'raghav@singhaniagroup.in', phone: '+91 98110 22456', message: '1930s bungalow conversion into a 12-key boutique wing. Conservation constraints apply to the lime-washed boundary walls and original jaali screens.', status: 'CONFIRMED', org: 'Singhania Group • Delhi', service: 'Boutique Hotel Wing', scope: 'Scope: 12 keys, facade & spatial planning', location: 'Civil Lines, Delhi', typology: 'Boutique Hotel Wing', footprint: '6,500 sq.ft', budget: '₹52,00,000', brief: '1930s bungalow conversion into a 12-key boutique wing. Conservation constraints apply to the lime-washed boundary walls and original jaali screens.', address: 'Amsterdam House, Civil Lines, Delhi 110006', ref: '#ENG-9027', assignee: { initials: 'ER', name: 'Elena Rostova', role: 'Lead Spatial Curator' }, ip: '14.139.72.190' },
  { name: 'Priya Nair', email: 'priya@alibaugliving.in', phone: '+91 98330 55678', message: 'Monsoon-exposed coastal plot with mature palm cover. Requires raised plinth detailing, laterite retaining walls and a salt-tolerant landscape strategy.', status: 'ARCHIVED', org: 'Alibaug Living Pvt. Ltd.', service: 'Coastal Villa Retreat', scope: 'Scope: Architecture & landscape turnkey', location: 'Alibaug, Maharashtra', typology: 'Coastal Villa Retreat', footprint: '5,200 sq.ft', budget: '₹64,00,000', brief: 'Monsoon-exposed coastal plot with mature palm cover. Requires raised plinth detailing, laterite retaining walls and a salt-tolerant landscape strategy.', address: 'Kihim Beach Road, Alibaug, MH 402201', ref: '#ENG-9019', assignee: { initials: 'NK', name: 'Nikhil Kulkarni', role: 'Landscape Director' }, ip: '117.198.44.63' },
  { name: 'Devendra Rathore', email: 'devendra@rajasthanheritage.in', phone: '+91 94140 33129', message: 'Degraded courtyard pavilion with carved sandstone columns. Restoration must follow conservation-grade protocols and source matching Rajnagar stone.', status: 'NEW', org: 'Rajasthan Heritage Craft Trust', service: 'Heritage Haveli Pavilion', scope: 'Scope: Courtyard restoration + stone carving', location: 'Udaipur, Rajasthan', typology: 'Heritage Haveli Pavilion', footprint: '7,400 sq.ft', budget: '₹41,00,000', brief: 'Degraded courtyard pavilion with carved sandstone columns. Restoration must follow conservation-grade protocols and source matching Rajnagar stone.', address: 'Gangaur Ghat Marg, Udaipur, RJ 313001', ref: '#ENG-9008', assignee: { initials: 'SV', name: 'Sanjana Verma', role: 'Conservation Architect' }, ip: '45.112.190.28' },
];

const testimonials = [
  { name: 'Rohan Malhotra', company: 'ABC Hospitality', rating: 5, quote: 'Outset Studio transformed our boutique hotel into a timeless brutalist sanctuary. The balance of raw concrete and warm teak wood exceeded our board\'s expectations.', initials: 'RM', avatar: 'sage', project: 'Rae Hotel Delhi', typology: 'Boutique Hotel • Delhi', status: 'pending', active: false },
  { name: 'Priya Nair', company: 'Nair Heritage Living', rating: 5, quote: 'Exceptional attention to natural light and local sandstone. The team respected our tight handover schedule while delivering uncompromised detailing.', initials: 'PN', avatar: 'blush', project: 'Komorebi Villa', typology: 'Alibaug Coastal • Residential', status: 'pending', active: false },
  { name: 'Vikram Singhania', company: 'Apex Studio Spaces', rating: 5, quote: 'A masterclass in acoustic privacy and refined executive interiors. Our tenants constantly compliment the materiality.', initials: 'VS', avatar: 'stone', project: 'The Work Loft', typology: 'Gurgaon Workspace • Commercial', status: 'pending', active: false },
  { name: 'Tanya Sharma', company: 'Kala Craft Collective', rating: 5, quote: 'Quiet luxury at its finest. They understood our brand heritage deeply and translated it into retail architecture.', initials: 'TS', avatar: 'blush', project: 'Artisanal Store', typology: 'Jaipur Flagship • Retail Monograph', status: 'approved', active: true },
  { name: 'Karan Mehta', company: 'Mehta F&B Group', rating: 5, quote: 'Flawless spatial flow and kitchen ergonomics. Highly recommended for commercial culinary spaces.', initials: 'KM', avatar: 'sage', project: 'Nova Café', typology: 'Mumbai Coastal • Hospitality', status: 'approved', active: true },
];

const vendors = [
  { vendorName: 'Jaipur Heritage Crafts', fullName: 'Jaipur Heritage Crafts & Stone', founder: 'Maheshwar Sharma', founderTitle: 'Master Artisan & Founder', phone: '+91 98290 11442', email: 'trade@jaipurstonecraft.in', gstNumber: '08AAACJ4921IMZ5', services: ['Lime Plaster', 'Stone Carving'], status: 'UNDER SCRUTINY', trade: 'LIME PLASTER & STONE', location: 'Jaipur, Rajasthan', action: 'REVIEW', workshop: ['RIICO Ind. Area, Mansaravar', 'Jaipur, Rajasthan 302020'], msme: 'UDYAM-RJ-17-004921Z2', msmeNote: 'Valid to 2028', gstinVerified: true, capabilities: ['Traditional Slaked Lime (Chuna) Arish', 'Hand-carved Sandstone Jali', 'Heritage Structural Restoration', 'Basalt & Travertine Masonry'], capacityStats: ['35 Guild Artisans', '12,000 sq. ft Yard', '4 Kilns'], files: [{ name: 'Stone_Craft_', size: '14.2 MB Dossier', icon: 'fa-file-lines' }, { name: 'Material_Test_Repc', size: '3.8 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Material Provenance & Quarry Source', desc: 'Bansi Pahar & Dholpur quarry certificates valid.', checked: false }, { title: 'Quality Audit of Past Heritage Restorations', desc: 'Verified on-site work at Mandawa Haveli restoration.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Artisan insurance declaration awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 1: PREFERRED' }, remarks: 'Passed sample masonry inspections in Jaipur. Aarish plaster samples verified by Studio Materials Lab on 25 Sep 2026.' },
  { vendorName: 'Moradabad Brass & Guild', fullName: 'Moradabad Brass & Guild Works', founder: 'Anwar Qureshi', founderTitle: 'Master Founder & Guild Head', phone: '+91 94120 78219', email: 'anwar@mbadbrasswork.com', gstNumber: '09AABCM7845K1Z9', services: ['Brass Casting', 'Metal Fabrication'], status: 'UNDER SCRUTINY', trade: 'BRASS & METAL FABRICATION', location: 'Moradabad, UP', action: 'VERIFY', workshop: ['Rustam Nagar Industrial Belt', 'Moradabad, Uttar Pradesh 244001'], msme: 'UDYAM-UP-23-0078412', msmeNote: 'Valid to 2028', gstinVerified: true, capabilities: ['Lost-wax Brass Casting', 'Hand Beaten Metal Cladding', 'Decorative Iron & Brass Inlay', 'Antique Metal Restoration'], capacityStats: ['62 Guild Artisans', '18,000 sq. ft Yard', '6 Furnaces'], files: [{ name: 'Brass_Guild_Dossier', size: '11.6 MB Dossier', icon: 'fa-file-lines' }, { name: 'Metal_Test_Report', size: '2.9 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Material Provenance & Alloy Source', desc: 'Certified brass ingot suppliers verified.', checked: false }, { title: 'Quality Audit of Past Commissions', desc: 'Reference installations pending site audit.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Artisan insurance declaration awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 2: VERIFIED' }, remarks: 'Initial document pack received. Awaiting physical sample submission to Studio Materials Lab.' },
  { vendorName: 'Deodar Timber & Joinery', fullName: 'Deodar Timber & Joinery Works', founder: 'Tenzing Dorjee', founderTitle: 'Principal Joiner & Founder', phone: '+91 97361 44520', email: 'projects@deodarjoinery.in', gstNumber: '05AAKCD9217L1ZP', services: ['Millwork', 'Joinery'], status: 'UNDER SCRUTINY', trade: 'ARCHITECTURAL MILLWORK', location: 'Dehradun / Delhi', action: 'VERIFY', workshop: ['Rajpur Road Millwork Cluster', 'Dehradun, Uttarakhand 248009'], msme: 'UDYAM-UK-04-0031876', msmeNote: 'Valid to 2027', gstinVerified: true, capabilities: ['Architectural Door & Window Millwork', 'Precision Panel Joinery', 'Heritage Timber Repair', 'Custom Furniture Fabrication'], capacityStats: ['48 Artisans', '9,500 sq. ft Workshop', '3 Kilns'], files: [{ name: 'Timber_Joinery_Dossier', size: '9.8 MB Dossier', icon: 'fa-file-lines' }, { name: 'Moisture_Test_Report', size: '2.1 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Timber Provenance & FSC Source', desc: 'Sourced teak & deodar chain-of-custody pending.', checked: false }, { title: 'Quality Audit of Past Joinery Works', desc: 'Two reference sites queued for inspection.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Artisan insurance declaration awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 2: VERIFIED' }, remarks: 'Millwork drawings portfolio received. Physical joinery samples requested for lab verification.' },
  { vendorName: 'Terra Cotta Atelier Delhi', fullName: 'Terra Cotta Atelier Delhi', founder: 'Suhasini Sen', founderTitle: 'Ceramic Artist & Founder', phone: '+91 98110 33901', email: 'atelier@senpottery.co', gstNumber: '07AASFS6634R1ZK', services: ['Terrazzo', 'Tile'], status: 'UNDER SCRUTINY', trade: 'HERITAGE TERRAZZO & TILE', location: 'Delhi NCR', action: 'VERIFY', workshop: ['Okhla Phase III Craft Cluster', 'New Delhi, Delhi 110020'], msme: 'UDYAM-DL-02-0056119', msmeNote: 'Valid to 2028', gstinVerified: true, capabilities: ['Handmade Heritage Terrazzo', 'Glazed Terracotta Tile', 'Mosaic Inlay Flooring', 'Custom Clay Facade Elements'], capacityStats: ['24 Artisans', '7,200 sq. ft Yard', '2 Kilns'], files: [{ name: 'Terrazzo_Atelier_Dossier', size: '8.4 MB Dossier', icon: 'fa-file-lines' }, { name: 'Tile_Flex_Test_Report', size: '1.9 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Aggregate & Pigment Provenance', desc: 'Marble chip suppliers under review.', checked: false }, { title: 'Quality Audit of Past Installations', desc: 'Three reference floors pending verification.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Artisan insurance declaration awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 2: VERIFIED' }, remarks: 'Tile sample kit received at Delhi HQ. Flexural strength test scheduled with Studio Materials Lab.' },
  { vendorName: 'Apex Façade & Glazing', fullName: 'Apex Façade & Glazing Pvt Ltd', founder: 'Vikramaditya Rao', founderTitle: 'Founder & Head of Engineering', phone: '+91 98201 55940', email: 'engg@apexglazing.com', gstNumber: '27AAHCA8821M1ZQ', services: ['Glazing', 'Acoustics'], status: 'UNDER SCRUTINY', trade: 'ACOUSTIC & GLAZING', location: 'Mumbai, MH', action: 'REVIEW', workshop: ['Andheri East Industrial Estate', 'Mumbai, Maharashtra 400093'], msme: 'UDYAM-MH-23-0112845', msmeNote: 'Valid to 2028', gstinVerified: true, capabilities: ['Structural Glazing Systems', 'Acoustic Glass Partitioning', 'Unitized Façade Modules', 'Bird-safe & Solar Glass Retrofit'], capacityStats: ['85 Engineers', '22,000 sq. ft Plant', '5 CNC Lines'], files: [{ name: 'Facade_Glazing_Dossier', size: '16.1 MB Dossier', icon: 'fa-file-lines' }, { name: 'Acoustic_Test_Certificate', size: '4.2 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Glass & Profile Provenance', desc: 'Float glass supplier audit in progress.', checked: false }, { title: 'Quality Audit of Past Façades', desc: 'Two tower references scheduled for inspection.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Worker safety dossier awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 1: PREFERRED' }, remarks: 'Engineering dossier and acoustic test certificates received. On-site audit of Andheri plant proposed.' },
  { vendorName: 'Marwar Marbles & Granite', fullName: 'Marwar Marbles & Granite Co.', founder: 'Bhanwar Singh', founderTitle: 'Quarry Owner & Managing Partner', phone: '+91 94141 88302', email: 'quarry@marwarmarble.in', gstNumber: '08AAFCM5512N1ZT', services: ['Marble', 'Granite'], status: 'UNDER SCRUTINY', trade: 'ARCHITECTURAL MASONRY', location: 'Jodhpur, Rajasthan', action: 'VERIFY', workshop: ['Madanganj Quarry Belt', 'Jodhpur, Rajasthan 342015'], msme: 'UDYAM-RJ-19-0067304', msmeNote: 'Valid to 2027', gstinVerified: true, capabilities: ['Dholpur Sandstone Blocks', 'Marble Slab Processing', 'CNC Stone Cutting', 'Heritage Masonry Restoration'], capacityStats: ['54 Artisans', '40,000 sq. ft Yard', '2 Saw Lines'], files: [{ name: 'Marwar_Masonry_Dossier', size: '12.7 MB Dossier', icon: 'fa-file-lines' }, { name: 'Stone_Compression_Report', size: '3.1 MB Lab Certificate', icon: 'fa-flask' }], checklist: [{ title: 'Business & Tax Identity Authenticated', desc: 'Active GSTIN, PAN matching Ministry records.', checked: true }, { title: 'Quarry Lease & Provenance Source', desc: 'Lease documents under legal review.', checked: false }, { title: 'Quality Audit of Past Masonry Works', desc: 'Reference haveli project pending inspection.', checked: false }, { title: 'Worksite Safety & Guild Fair-Wage Compliance', desc: 'Artisan insurance declaration awaiting sign-off.', checked: false }], curator: { name: 'Elena Vance', role: 'Principal Director • Delhi HQ Admin', tier: 'TIER 2: VERIFIED' }, remarks: 'Quarry documentation received. Compression test samples dispatched to Studio Materials Lab.' },
];

async function seed() {
  await connectDB();

  const existingAdmin = await Admin.findOne({ email: 'admin@outsetstudio.in' });
  if (!existingAdmin) {
    await Admin.create({ email: 'admin@outsetstudio.in', password: 'admin123', name: 'Admin', title: 'Administrator', location: 'Delhi HQ', initials: 'AD' });
    console.log('Admin created');
  } else {
    console.log('Admin already exists, skipped');
  }

  const counts = {};
  const insertMissing = async (Model, data, keyField) => {
    let n = 0;
    for (const doc of data) {
      const q = {};
      q[keyField] = doc[keyField];
      if (!(await Model.exists(q))) {
        await Model.create(doc);
        n++;
      }
    }
    return n;
  };
  counts.projects = `${await insertMissing(Project, projects, 'slug')} added`;
  counts.contacts = `${await insertMissing(Contact, contacts, 'ref')} added`;
  counts.testimonials = `${await insertMissing(Testimonial, testimonials, 'project')} added`;
  counts.vendors = `${await insertMissing(Vendor, vendors, 'vendorName')} added`;

  // Migrate legacy docs (created via public API without admin fields)
  await Contact.updateMany({ status: { $exists: false } }, { $set: { status: 'NEW', read: false } });
  await Vendor.updateMany({ status: { $exists: false } }, { $set: { status: 'NEW', read: false } });
  await Testimonial.updateMany({ status: { $exists: false }, active: true }, { $set: { status: 'approved' } });
  await Testimonial.updateMany({ status: { $exists: false } }, { $set: { status: 'pending' } });
  await Project.updateMany({ status: { $exists: false } }, { $set: { status: 'Completed', progress: 100 } });
  console.log('Legacy migration complete');

  console.log('Seed complete:', counts);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
